export const ENTITY = {
  brand: "PurePep",
  domain: "purepep.shop",
  legalName: "JAECOM GK",
  legalNameJa: "JAECOM 合同会社",
  entityType: "Gōdō Kaisha (合同会社)",
  corporateNumber: "9120103007079",
  country: "Japan",
  countryCode: "JP",
  address: {
    line1: "315 Harada",
    line2: "Nishi-ku, Sakai-shi",
    region: "Osaka",
    postalCode: "593-8317",
    country: "Japan",
    countryCode: "JP",
    full: "315 Harada, Nishi-ku, Sakai-shi, Osaka 593-8317, Japan",
    fullJa: "〒593-8317 大阪府堺市西区原田315",
  },
  email: "info@purepep.shop",
  website: "https://purepep.shop",
  minimumAge: 21,
  useStatement: "For Research Use Only — Not for Human Consumption",
  audience: "qualified researchers aged 21 or older",
  phoneDisplay: "(866) 212-6466",
  phoneTel: "+18662126466",
} as const;
